### ISSUE TITLE
OutGridView.Gui Crashes on MacOS 11.1

### ISSUE THREAD

**Issue by ryguy77** [PowerShell/GraphicalTools#138]
Unable to run simple grid view on MacOS 11.1. The command runs the processor hard then it will crash the app. Running the following command: 
ps | Microsoft.PowerShell.GraphicalTools\Out-GridView
Attached is the crash report. 
[OutGridView.Gui_2021-02-08-134211_.txt](https://github.com/PowerShell/GraphicalTools/files/5946044/OutGridView.Gui_2021-02-08-134211_.txt)

Running Powershell Core 7.1.1
Microsoft.PowerShell.GraphicalTools 0.2.0

**Comment by tig** [comment]
Can you please pull down PR #141 and test this?

Thanks a ton!

**Comment by tig** [comment]
Fixed by #141

**Comment by yllekz** [comment]
Was this pushed? out-gridview still hangs in macOS, after a fresh pull from the PSGallery.

**Comment by TylerLeonhardt** [comment]
@tig is talking about ConsoleGuiTools... this issue is about _GraphicalTools_. Please see: https://github.com/PowerShell/GraphicalTools/issues/101

**Comment by tig** [comment]
@andschwa This should be closed as won't fix since it's for the Avalona version.
